# Copyright (c) 2025, NVIDIA CORPORATION. All rights reserved.
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# YAML anchors for shared configurations
x-spark-common: &spark-common
  volumes:
    - ${DATA_DIR:-${PWD}/data}:/data

services:
  spark-connect-client:
    <<: *spark-common
    image: spark-connect-client-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-connect-client
    hostname: spark-connect-client
    network_mode: host
    environment:
      - SPARK_REMOTE=${SPARK_REMOTE:-sc://localhost}
    command: >
      bash -c
      'jupyter-lab
      --port 8888
      --no-browser
      --IdentityProvider.token=""
      --ServerApp.password=""
      --ServerApp.ip='0.0.0.0'
      --ServerApp.allow_origin='*' '
